### ISSUE TITLE
puppeteerLaunchOptions is not working

### ISSUE THREAD

**Issue by nishimura-yuji** [scullyio/scully#194]
# 🐞 Bug report

puppeteerLaunchOptions is setting from configuration file does not work.

I want to set```--no-sandbox```.

So, Added settings to ```scully.config.js```

But, Not working. 

I think that ```scullyConfig.puppeteerLaunchOptions``` is undefinded.

https://github.com/scullyio/scully/blob/f81c560ad568898027ca1efb9025269a78c67895/scully/renderPlugins/launchedBrowser.ts#L18

## 🔬 Minimal Reproduction

add ```puppeteerLaunchOptions```

scully.config.js 

<pre>
exports.config = {
  projectRoot: './src/app',
  puppeteerLaunchOptions: {
    args: ['--no-sandbox', '--disable-setuid-sandbox']
  },
  outFolder: './dist/static',
  routes: {
    '/blog/:slug': {
      type: 'contentFolder',
      slug: {
        folder: './blog'
      }
    }
  }
};
</pre>

## 💻Your Environment 
**Angular Version:**
<pre>
Angular CLI: 9.0.0-rc.9
Node: 12.13.0
OS: darwin x64

Angular: 9.0.0-rc.9
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.9
@angular-devkit/build-angular     0.900.0-rc.9
@angular-devkit/build-optimizer   0.900.0-rc.9
@angular-devkit/build-webpack     0.900.0-rc.9
@angular-devkit/core              9.0.0-rc.9
@angular-devkit/schematics        9.0.0-rc.9
@angular/cdk                      8.2.3
@angular/material                 8.2.3
@ngtools/webpack                  9.0.0-rc.9
@schematics/angular               9.0.0-rc.9
@schematics/update                0.900.0-rc.9
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2
</pre>

**Scully Version:**
<pre>    "@scullyio/init": "0.0.14",
    "@scullyio/ng-lib": "latest",
    "@scullyio/scully": "latest",
</pre>
## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by SanderElias** [comment]
@nishimura-yuji I just pushed out new versions, can you update your packages and test again.
Please let us know, and if it works, can you close the issue?

**Comment by jorgeucano** [comment]
I will close this issue... @nishimura-yuji if you have another error please create a new ticket or re-open this! thanks

**Comment by BlindDespair** [comment]
This is still an issue, I am experiencing the same. `function obsBrowser(options = config_1.scullyConfig.puppeteerLaunchOptions || {})` has `scullyConfig` as an empty object... I checked config.js and there is such a thing as `compiledConfig` and that one contains everything I need. But it's inside an async function and I am not sure when it's called by launchedBrowser clearly tries to access config before it was set. 
![image](https://user-images.githubusercontent.com/15785773/73618261-ae962b00-4626-11ea-82d5-d6fe75708f2a.png)

**Comment by BlindDespair** [comment]
I tried it with latest version of scully and can confirm that it works now, also managed to build it in docker.
