### ISSUE TITLE
TransferState does not correctly handle current URL with query params

### ISSUE THREAD

**Issue by BlindDespair** [scullyio/scully#439]
### Description
When navigating to a prerendered page with query params scully fails to fetch page data because the url for fetching the data is not created correctly.

The issue can be fixed [here](https://github.com/scullyio/scully/blob/3596179e222c28abe17a0a7e59579e4144bc8efc/projects/scullyio/ng-lib/src/lib/transfer-state/transfer-state.service.ts#L205)

I can suggest to do something like adding this before `switchMap(url => ...)`
```
map(url => url.replace(/(\?.*)|(#.*)/g, ""))
```
But perhaps it can be done cleaner, since you know the codebase better.

#### 🔬 Minimal Reproduction
1. Have an app prerendered by scully
2. Navigate to e.g. `/successful-order?orderId=24`

Scully will try to fetch data from:
`/successful-order?orderId=24/data.json`
but should from:
`/successful-order/data.json`

The query parameters must be escaped.

#### 💻Your Environment

**Angular Version:**

<pre><code>

Angular CLI: 9.0.2
Node: 12.14.0
OS: linux x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.0-rc.8
@angular-devkit/schematics        9.0.0-rc.8
@angular/cdk                      9.0.0
@angular/cli                      9.0.2
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.0-rc.8
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Scully Version:**

<pre><code>

"@scullyio/init": "0.0.13",
"@scullyio/ng-lib": "0.0.22",
"@scullyio/scully": "0.0.86",

</code></pre>

**Comment by SanderElias** [comment]
@BlindDespair can you explain to me how you would expect the data to be there?
your example: `/successful-order?orderId=24` would get the same data as `/successful-order?orderId=1` and _all_ other `orderid=xxx` 
If you rework your code to do something like `/successful-order/24` it can pre-render all permutations. 

I'll add something to ignore query parameters nevertheless, but you should use them only for modifiers, not for things that fetch data.

**Comment by BlindDespair** [comment]
@SanderElias the param in this case does not affect the prerendered data, that param is only for runtime purpose there. That's why prerendered page should be same in all cases.

**Comment by wickstargazer** [comment]
Hi, I am also seeing this issue, the json that needs to render translations from state is not working with query params, like `url/?fbclid=test`

**Comment by jorgeucano** [comment]
Fixed

**Comment by MikeOne** [comment]
Hey Jorge - in which release do you expect this fix to be in?

**Comment by MikeOne** [comment]
@jorgeucano @SanderElias - I'm still seeing this issue in the latest version. Would you like me to raise a new issue or can this one be re-opened? And can maybe someone confirm this is indeed not fixed in the current version (0.0.92 | 0.0.22)?

**Comment by jorgeucano** [comment]
@MikeOne Sander is working on it!

**Comment by camilodavilabonilla** [comment]
@jorgeucano @SanderEliasI would like know the response of this case because I still with the same issue my currentversion
"@scullyio/init": "1.0.1",
"@scullyio/ng-lib": "1.0.2",
"@scullyio/scully": "1.1.0",

**Comment by SanderElias** [comment]
@camilodavilabonilla Can you please make a new issue for this, reference this, and it does help if there is an way to reproduce the issue quickly. 
As far as I can remember this issue is fixed, but I might remember wrongly, a lot can happen in a year.
