### ISSUE TITLE
scully-content does not update when routing between two components which both have scully-content 

### ISSUE THREAD

**Issue by bufke** [scullyio/scully#797]
## 🐞 Bug report

Continuing conversation from https://github.com/scullyio/scully/issues/311#issuecomment-665373714

#### 🔬 Minimal Reproduction

https://gitlab.com/bufke/scully-content-not-loaded

- Build and serve scully
- Go to http://localhost:1668/blog/this-is-my-post
- Notice the link to a news post. Click it
- You are navigated to http://localhost:1668/news/2020-07-29-news

However scully-content renders the previous page's blog content saying "another blog post" instead of the news post content.

**Scully Version:**

1.0.0-beta.0

**Comment by SanderElias** [comment]
This issue is solved by #779, and waiting for release.

**Comment by KaliaHayes** [comment]
> This issue is solved by #779, and waiting for release.

Has the solution to the routing issue been released? I'm experiencing it on the latest version of Scully nearly 3 years later.

**Comment by EricHurt** [comment]
I am still experiencing this issue as well. Any updates @SanderElias?

**Comment by EricHurt** [comment]
This issue is affecting notiz.dev as well, one of the featured websites using scully. Can we have an update on this? @aaronfrost @SanderElias
